# Generated by Django 5.0.2 on 2024-02-29 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jokes', '0002_joke_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='dummy',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
