# Generated by Django 5.0.2 on 2024-02-29 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jokes', '0003_tag_dummy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='dummy',
        ),
    ]
